### ISSUE TITLE
Create Bootstrap modal dialog 

### ISSUE THREAD

**Issue by tayskully** [rossgilman402/project-tracker#13]
##task 1 html build 
#2.
- [x] create bootstrap card component
- [ ] must include instructions on how to use the app
- [ ] must include button to open a bootstrap modal dialog
